version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    depends_on:
      - ollama
      - qdrant

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    volumes:
      - ./crawler:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  ollama_data:
  qdrant_data:

networks:
  ireland_travel_network:
    driver: bridge 